config/routes.rb
Vball::Application.routes.draw do
  root :to => "sessions#login"

  match "/login" => "sessions#login"

  resources :teams
  resources :seasons
  match "/seasons/season_change" => "seasons#season_change"
  
  resources :players
  resources :matches

  

end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :players
  has_many :matches

  def upcoming_matches
    self.matches.order('match_date DESC').limit(5)
  end

  #id
  #year
  #created_at
  #updated_at
  #team_id
end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  
  def index
    @seasons = Team.find(params[:team_id]).seasons

    respond_to do |format|
      format.html # index.html.erb
      format.xml { render :xml => @seasons }
    end
  end

  def season_change
    session[:current_season] = params[:season]
    results = "changed"
    render :text=>results.to_json
  end

end

app/views/seasons/_form.html.erb
<%= form_for(@season) do |f| %>
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@season.errors.count, "error") %> prohibited this season from being saved:</h2>

      <ul>
      <% @season.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.text_field :year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Editing season</h1>

<%= render 'form' %>

<%= link_to 'Show', @season %> |
<%= link_to 'Back', seasons_path %>

app/views/seasons/index.html.erb
<h1>Listing seasons</h1>

<table>
  <tr>
    <th>Year</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @seasons.each do |season| %>
  <tr>
    <td><%= season.year %></td>
    <td><%= link_to 'Show', season %></td>
    <td><%= link_to 'Edit', edit_season_path(season) %></td>
    <td><%= link_to 'Destroy', season, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Season', new_season_path %>

app/views/seasons/new.html.erb
<h1>New season</h1>

<%= render 'form' %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/season_schedule.html.erb
<h1>Schedule</h1>


<% @matches.each do |team| %>
  team.opponent <br/>
<% end %>

app/views/seasons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Year:</b>
  <%= @season.year %>
</p>


<%= link_to 'Edit', edit_season_path(@season) %> |
<%= link_to 'Back', seasons_path %>